version: 2
jobs:
  build:
    branches:
      ignore:
        - master # only test new branches
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: # run tests
          name: test
          command: npm run test:tofile
      - run: # run link
          name: lint
          command: npm run lint:tofile

      - store_test_results:
          path: reports/xunit
      - store_artifacts:
          path: reports/xunit
